### ISSUE TITLE
Baza danych sqlite dla benchmarków oraz poetry, docker, README

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/Benchmark_LLM#2]
## Jaki jest cel tego tego zadania

Stworzenie i konfiguracja bazy danych SQLite w kontekście benchmarków dla modeli (LLM), służącej do przechowywania data setów, wyników i danych związanych z benchmarkami

## Jak wygląda rozwiązanie?

Rozwiązanie polega na stworzeniu bazy danych SQLite w formie pliku, który zostanie umieszczony w repozytorium projektu. Baza danych będzie zawierać strukturę i dane potrzebne do przeprowadzania benchmarków.

## TODO

Baza Danych:

 - [ ] Utworzenie bazy danych SQLite
 - [ ] Określenie struktury bazy danych
 - [ ] Implementacja interfejsu do obsługi bazy
 - [ ] Integracja z benchmarkami LLM

Poetry:

- [x] Wybranie paczek
- [x] uzupełnienie autora itp
- [x] Napisanie README 

docker:

- [x] Dockerfile
- [x] doceker-compose 
- [x] Napisanie README

**Comment by Kleczyk** [comment]
#14 zrobiona część z poetry docker oraz README
pls review
