### ISSUE TITLE
Benchmark Programowania

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/Benchmark_LLM#7]
## Jaki jest cel tego tego zadania

Celem tego zadania jest stworzenie benchmarku który sprawdza umiejętności programowania modelu mogą to byś typowe problemy programistyczne jak sortowanie rekurencja itp  w różnych językach 

## Jak wygląda rozwiązanie?

Rozwiązanie polega na stworzeniu gotowego skryptu, który będzie działał w sposób ciągły. Skrypt ten będzie pobierał dane z bazy danych, przeprowadzał benchmark na bieżąco, rejestrował parametry, odpowiedzi modeli i przesyłał te dane do bazy danych.

## TODO:

- [ ] Określenie koncepcji testu
- [ ] Przygotowanie odpowiedniego zbioru danych
- [ ] Napisanie skryptu do przeprowadzania benchmarków
- [ ] Integracja skryptu z bazą danych

## Powiązane taski/bugi
#1
